import React, { useState } from 'react';
import { generatePlans, isConfigured } from '../services/gemini';

const PlanCard = ({ title, items, type }) => (
    <div className="glass-card p-6 h-full">
        <div className="flex justify-between items-center mb-6">
            <h3 className="text-2xl font-bold text-white">{title}</h3>
            <span className={`px-3 py-1 rounded-full text-xs font-bold ${type === 'workout' ? 'bg-secondary/20 text-secondary' : 'bg-primary/20 text-primary'
                }`}>
                {type === 'workout' ? 'ACTIVE' : 'DIET'}
            </span>
        </div>
        <div className="space-y-4">
            {items.map((item, idx) => (
                <div key={idx} className="p-4 rounded-xl bg-white/5 hover:bg-white/10 transition-colors cursor-pointer group">
                    <div className="flex justify-between items-start mb-2">
                        <h4 className="font-bold text-white group-hover:text-primary transition-colors">{item.name}</h4>
                        <span className="text-xs text-gray-400">{item.meta}</span>
                    </div>
                    <p className="text-sm text-gray-400">{item.desc}</p>
                </div>
            ))}
        </div>
    </div>
);

const Plans = () => {
    const [isLoading, setIsLoading] = useState(false);
    const [workouts, setWorkouts] = useState([
        { name: 'Morning HIIT', meta: '20 min • High Intensity', desc: 'Jump squats, Burpees, Mountain Climbers' },
        { name: 'Core Strength', meta: '15 min • Medium', desc: 'Planks, Crunches, Leg Raises' },
        { name: 'Evening Yoga', meta: '30 min • Low', desc: 'Sun Salutation, Warrior Pose, Child Pose' },
    ]);

    const [meals, setMeals] = useState([
        { name: 'Oatmeal & Berries', meta: '350 kcal • Breakfast', desc: 'Rolled oats, almond milk, blueberries, chia seeds' },
        { name: 'Grilled Chicken Salad', meta: '450 kcal • Lunch', desc: 'Chicken breast, mixed greens, avocado, olive oil' },
        { name: 'Salmon & Asparagus', meta: '500 kcal • Dinner', desc: 'Baked salmon, steamed asparagus, quinoa' },
    ]);

    const handleGenerate = async () => {
        if (!isConfigured()) {
            alert("Please configure your VITE_GEMINI_API_KEY in the .env file first.");
            return;
        }

        setIsLoading(true);
        try {
            // Mock user stats
            const userStats = {
                steps: 8432,
                calories: 1850,
                water: 1.2,
                sleep: "7h 20m"
            };

            const plans = await generatePlans(userStats);
            if (plans.workout) setWorkouts(plans.workout);
            if (plans.diet) setMeals(plans.diet);
        } catch (error) {
            console.error(error);
            alert("Failed to generate plans. Please try again.");
        } finally {
            setIsLoading(false);
        }
    };

    return (
        <div className="p-8 h-screen overflow-y-auto">
            <header className="mb-8 flex justify-between items-center">
                <div>
                    <h2 className="text-3xl font-bold text-white">Your Plans 📋</h2>
                    <p className="text-gray-400">Customized workout and diet plans generated by AI.</p>
                </div>
                <button
                    onClick={handleGenerate}
                    disabled={isLoading}
                    className="btn-primary flex items-center gap-2 disabled:opacity-50"
                >
                    {isLoading ? (
                        <>
                            <span className="animate-spin">⏳</span> Generating...
                        </>
                    ) : (
                        <>
                            <span>✨</span> Generate New Plans
                        </>
                    )}
                </button>
            </header>

            <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
                <PlanCard title="Weekly Workout" items={workouts} type="workout" />
                <PlanCard title="Nutrition Plan" items={meals} type="diet" />
            </div>
        </div>
    );
};

export default Plans;
